Seller functionality
Priyanshijain2509/shopsy pull request #1
Opened 2023-10-20 12:04 UTC by Priyanshijain2509

Implemented all the functionality assigned in the task like
seller functionality
- item creation page
- A Seller can only edit or see items created by himself
- seller dashboard
buyer functionality
- All item page
- order button with ajax implemented
- order/cancel confirmation mail
Admin functionality
- can see and delete all users
- can see and delete all items

2023-10-26 10:16 UTC, Nitish3119 requested changes

2023-10-26 10:16 UTC, Nitish3119 commented on app/controllers/orders_controller.rb
> +    @user_id = current_user.id
If you are not using @user_id in this method further than why are you storing it. Please remove it if you are not using it.

2023-10-26 10:16 UTC, Nitish3119 commented on app/controllers/orders_controller.rb
> +    @user_id = current_user.id
If you are not using @user_id in this method further than why are you storing it. Please remove it if you are not using it.

2023-10-26 10:16 UTC, Nitish3119 commented on app/controllers/orders_controller.rb
> +    @user_id = current_user.id
If you are not using @user_id in this method further than why are you storing it. Please remove it if you are not using it.

2023-10-26 10:16 UTC, Nitish3119 commented on app/mailers/order_mailer.rb
> +    mail(to: user.email, subject: 'Order Confirmation')
here you are using 'user so why are you assigning @user above

2023-10-26 10:16 UTC, Nitish3119 commented on app/mailers/order_mailer.rb
> +    mail(to: user.email, subject: 'Order Cancellation')
here you are using 'user so why are you assigning @user above

2023-10-26 10:16 UTC, Nitish3119 commented on app/mailers/order_mailer.rb
> +    mail(to: user.email, subject: 'Order Cancellation')
here you are using 'user so why are you assigning @user above

2023-10-26 10:16 UTC, Nitish3119 commented on app/mailers/order_mailer.rb
> +    @order = order
you are not using @order and product so remove them

2023-10-26 10:16 UTC, Nitish3119 commented on test/controllers/items_controller_test.rb
> -  # test "the truth" do
remove these comment text

2023-10-26 10:25 UTC, Priyanshijain2509 commented on app/mailers/order_mailer.rb
> +    mail(to: user.email, subject: 'Order Confirmation')
because in order confirmation view file, i can access it with @user.

2023-10-26 10:26 UTC, Priyanshijain2509 commented on app/mailers/order_mailer.rb
> +    @order = order
Accessing them in order mailer view files

2023-10-27 06:35 UTC, aryansharma-16 commented on app/controllers/orders_controller.rb
> +      flash[:info] = "You'll recieve a order confirmation mail!"
use single quotes

2023-10-27 06:43 UTC, aryansharma-16 commented on app/controllers/orders_controller.rb
> +      flash[:error]= 'Order could not be placed'
add empty space on each side of =

2023-10-27 06:43 UTC, aryansharma-16 commented on app/controllers/orders_controller.rb
> +      flash[:info] = "You'll recieve a order cancellation mail!"
single quotes

2023-10-27 06:44 UTC, aryansharma-16 commented on app/controllers/products_controller.rb
> +      flash[:error] = "Product can't be created"
single quotes

2023-10-27 06:44 UTC, aryansharma-16 commented on app/controllers/products_controller.rb
> +      flash[:error] = "Product couldn't be updated"
single quotes

2023-10-27 06:46 UTC, aryansharma-16 commented on app/controllers/users_controller.rb
> +    flash[:success] = "User deleted"
single quotes

2023-10-27 06:47 UTC, aryansharma-16 commented on app/controllers/orders_controller.rb
> +class OrdersController < ApplicationController
add comments for class and every action

2023-10-27 06:47 UTC, aryansharma-16 commented on app/controllers/products_controller.rb
> +class ProductsController < ApplicationController
add comments for class and every action

2023-10-27 06:48 UTC, aryansharma-16 commented on app/controllers/users_controller.rb
add comments for class and every action

2023-10-27 06:48 UTC, aryansharma-16 commented on app/controllers/products_controller.rb
add comments for class and every action

2023-10-27 06:48 UTC, aryansharma-16 commented on app/controllers/orders_controller.rb
add comments for class and every action

2023-10-27 06:52 UTC, aryansharma-16 commented on app/mailers/order_mailer.rb
add comments for class and every action

2023-10-27 06:56 UTC, aryansharma-16 commented on app/views/devise/registrations/edit.html.erb
> +      <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %>
use proper indentation

2023-10-27 07:17 UTC, aryansharma-16 commented on app/views/devise/registrations/edit.html.erb
> +<div>Unhappy?
use proper indentation

2023-10-27 07:17 UTC, aryansharma-16 commented on app/views/devise/registrations/edit.html.erb
> -    method: :delete %></div>
use proper indentation

2023-10-27 07:17 UTC, aryansharma-16 commented on app/views/devise/registrations/new.html.erb
> +        resource_name)) do |f| %>
use proper indentation

2023-10-27 07:17 UTC, aryansharma-16 commented on app/views/devise/sessions/new.html.erb
> +  <%= form_for(resource, as: resource_name, url: session_path(
use proper indentation

2023-10-27 07:17 UTC, aryansharma-16 commented on config/database.yml
> -  username: ongraph
use env variables

2023-10-27 07:17 UTC, aryansharma-16 commented on config/database.yml
> +  username: priyanshi
use env variables

2023-10-27 07:17 UTC, aryansharma-16 commented on config/environments/development.rb
> +    password:             'xgjr aqzo pmza bfel',
use env variables

2023-10-27 07:17 UTC, aryansharma-16 commented on config/initializers/devise.rb
> +  config.mailer_sender = 'anytriangle@gmail.com'
use env variables

2023-10-27 07:17 UTC, aryansharma-16 commented on config/routes.rb
> +  get 'all_user', to: 'users#all_user', as: 'all_users'
use the rails defined actions

2023-10-27 07:17 UTC, aryansharma-16 commented on app/controllers/orders_controller.rb
> +# frozen_string_literal: true
add comments for class and every action

2023-10-27 07:17 UTC, aryansharma-16 commented on app/controllers/orders_controller.rb
> +      flash[:error]= 'Order could not be placed'
add empty space on each side of =

2023-10-27 07:17 UTC, aryansharma-16 commented on app/controllers/products_controller.rb
> +# frozen_string_literal: true
add comments for class and every action

2023-10-27 07:17 UTC, aryansharma-16 commented on app/controllers/users_controller.rb
>      @user = User.new
add comments for class and every action

2023-10-27 07:17 UTC, aryansharma-16 commented on app/controllers/users_controller.rb
> +    flash[:success] = "User deleted"
single quotes

2023-11-06 11:55 UTC, merged